services:
  - type: web
    name: abcd-project
    env: docker
    plan: free
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: abcd-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true

databases:
  - name: abcd-db
    plan: free
