"""empty message

Revision ID: 03ef39d08a05
Revises: 7eae1c3039e1
Create Date: 2025-07-21 10:40:33.329037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ef39d08a05'
down_revision = '7eae1c3039e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('idCliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('interes', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idCliente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('destino',
    sa.Column('idDestino', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idDestino')
    )
    op.create_table('idioma',
    sa.Column('idIdioma', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idIdioma')
    )
    op.create_table('servicio',
    sa.Column('idServicio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idServicio')
    )
    op.create_table('ciudad',
    sa.Column('idCiudad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.idDestino'], ),
    sa.PrimaryKeyConstraint('idCiudad')
    )
    op.create_table('curso',
    sa.Column('idCurso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('tipoCurso', sa.String(length=50), nullable=False),
    sa.Column('edades', sa.String(length=50), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('idioma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.idDestino'], ),
    sa.ForeignKeyConstraint(['idioma_id'], ['idioma.idIdioma'], ),
    sa.PrimaryKeyConstraint('idCurso')
    )
    op.create_table('curso_servicio',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.idCurso'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.idServicio'], ),
    sa.PrimaryKeyConstraint('curso_id', 'servicio_id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=80), nullable=False))

    op.drop_table('curso_servicio')
    op.drop_table('curso')
    op.drop_table('ciudad')
    op.drop_table('servicio')
    op.drop_table('idioma')
    op.drop_table('destino')
    op.drop_table('cliente')
    # ### end Alembic commands ###
