"""cambiar relacion curso-destino a muchos-a-muchos

Revision ID: 2b9607e7b5e2
Revises: 2bf08edc29f4
Create Date: 2025-11-26 13:55:30.480971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9607e7b5e2'
down_revision = '2bf08edc29f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso_destino',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.idCurso'], ),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.idDestino'], ),
    sa.PrimaryKeyConstraint('curso_id', 'destino_id')
    )
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('curso_destino_id_fkey'), type_='foreignkey')
        batch_op.drop_column('destino_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('curso_destino_id_fkey'), 'destino', ['destino_id'], ['idDestino'])

    op.drop_table('curso_destino')
    # ### end Alembic commands ###
