"""initial migration for Neon

Revision ID: 2bf08edc29f4
Revises: 
Create Date: 2025-10-20 13:12:16.039690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf08edc29f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('idCliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('interes', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idCliente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('destino',
    sa.Column('idDestino', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idDestino')
    )
    op.create_table('idioma',
    sa.Column('idIdioma', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idIdioma')
    )
    op.create_table('servicio',
    sa.Column('idServicio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idServicio')
    )
    op.create_table('testimonio',
    sa.Column('idTestimonio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('videoUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idTestimonio')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ciudad',
    sa.Column('idCiudad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.idDestino'], ),
    sa.PrimaryKeyConstraint('idCiudad')
    )
    op.create_table('curso',
    sa.Column('idCurso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('tipoCurso', sa.String(length=50), nullable=False),
    sa.Column('edades', sa.String(length=50), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('idioma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.idDestino'], ),
    sa.ForeignKeyConstraint(['idioma_id'], ['idioma.idIdioma'], ),
    sa.PrimaryKeyConstraint('idCurso')
    )
    op.create_table('curso_servicio',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.idCurso'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.idServicio'], ),
    sa.PrimaryKeyConstraint('curso_id', 'servicio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso_servicio')
    op.drop_table('curso')
    op.drop_table('ciudad')
    op.drop_table('usuario')
    op.drop_table('testimonio')
    op.drop_table('servicio')
    op.drop_table('idioma')
    op.drop_table('destino')
    op.drop_table('cliente')
    # ### end Alembic commands ###
